# Version info
node:
  worker-count: 3
  ip:
    m1-k8s: 192.168.2.10
    w1-k8s: 192.168.2.101
    w2-k8s: 192.168.2.102
    w3-k8s: 192.168.2.103
docker:
  versions:
    docker-ce: 5:20.10.14~3-0~ubuntu-focal
    docker-ce-cli: 5:20.10.14~3-0~ubuntu-focal
    containerd-io: 1.5.11-1
  registry:
    reg-ip: 192.168.2.10
    reg-port: 8443
kubernetes:
  versions:
    kube-version: 1.23.5
    kubectl: 1.23.5-00
    kubelet: 1.23.5-00
    kubeadm: 1.23.5-00
    kube-apiserver: v1.23.5
    kube-controller-manager: v1.23.5
    kube-scheduler: v1.23.5
    kube-proxy: v1.23.5
    pause: 3.6
    etcd: 3.5.1-0
    coredns: v1.8.6
  const:
    token: 123456.1234567890123456
    cidr: 172.16.0.0/16
calico: v3.22.1
