# Version info
node:
  worker-count: 3
  ip:
    m1-k8s: 192.168.1.10
    w1-k8s: 192.168.1.101
    w2-k8s: 192.168.1.102
    w3-k8s: 192.168.1.103
docker:
  versions:
    docker-ce:
    docker-ce-cli:
  registry:
    registry-port: 8443
kubernetes:
  versions:
    kube-version: 1.23.5
    kubectl: v1.23.5
    kubelet: v1.23.5
    kubeadm: v1.23.5
    kube-apiserver: v1.23.5
    kube-controller-manager: v1.23.5
    kube-scheduler: v1.23.5
    kube-proxy: v1.23.5
    pause: 3.6
    etcd: 3.5.1-0
    coredns: v1.8.6
  const:
    token: 123456.1234567890123456
    cidr: 172.16.0.0/16
calico: v3.22.1
